/*
 * dc_motor_math_params.c
 *
 * Hand-written file (NOT generated by Simulink Coder).
 *
 * The generated dc_motor_math model declares these as `extern` in
 * dc_motor_math_private.h but never defines them anywhere in the
 * generated sources -- normally Simulink bakes these in from MATLAB
 * workspace variables, but that step was skipped/not applicable here.
 *
 * Adjust the numeric values below to match your actual motor's
 * datasheet parameters. Units:
 *   R  - armature resistance       [Ohm]
 *   L  - armature inductance       [H]
 *   J  - rotor inertia             [kg*m^2]
 *   K  - torque/back-EMF constant  [N*m/A]  (Kt == Ke assumed equal, SI units)
 *   b  - viscous friction coeff    [N*m*s]
 *
 * Integrator1_IC = initial speed  [rad/s]
 * Integrator_IC  = initial current [A]
 */

#include "rtwtypes.h"

// real_T dc_motor_math_R = 2.0;          /* Ohm */
// real_T dc_motor_math_L = 0.05;         /* H   */
// real_T dc_motor_math_J = 0.0005;       /* kg*m^2 */
// real_T dc_motor_math_K = 0.1;          /* N*m/A (== V*s/rad) */
// real_T dc_motor_math_b = 0.0003;       /* N*m*s */

// real_T dc_motor_math_Integrator_IC  = 0.0;  /* initial current, A */
// real_T dc_motor_math_Integrator1_IC = 0.0;  /* initial speed, rad/s */


/* ConstVolatile memory section */
/* Definition for custom storage class: ConstVolatile */
 real_T dc_motor_math_Integrator1_IC = 0.0;/* Referenced by: '<Root>/Integrator1' */
 real_T dc_motor_math_Integrator_IC = 0.0;/* Referenced by: '<Root>/Integrator' */
 real_T dc_motor_math_J = 0.01;/* Referenced by: '<Root>/Inertia' */
 real_T dc_motor_math_K = 0.01;/* Referenced by:
                                              * '<Root>/Ke'
                                              * '<Root>/Kt'
                                              */
 real_T dc_motor_math_L = 0.5;/* Referenced by: '<Root>/Inductance' */
 real_T dc_motor_math_R = 1.0;/* Referenced by: '<Root>/Resistance' */
 real_T dc_motor_math_b = 0.1;/* Referenced by: '<Root>/Damping' */