# Shell subsystem
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_RING_BUFFER=y

# (Optional) Change the shell prompt from "uart:~$" to something custom
CONFIG_SHELL_PROMPT_UART="blackpill:~$ "

CONFIG_SHELL_VT100_COLORS=n

# # Disable echo — critical for Python library parsing later
# CONFIG_SHELL_ECHO_STATUS=n

# Logging (optional, useful for debug)
CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_GPIO=y

CONFIG_ADC=y
CONFIG_ADC_STM32=y

CONFIG_SPI=y

CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_RING_BUFFER=y

CONFIG_PWM=y
CONFIG_PWM_CAPTURE=y   # if supported by the STM32 HAL for your Zephyr version
CONFIG_COUNTER=y       # used internally by PWM capture


 # Motor simulation needs floating point + math.h (fabs, etc.)
CONFIG_FPU=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y   # required for %f-ish int-decomposed prints to work cleanly
# Workqueue used to defer model stepping out of timer ISR context
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
